# Generated by Django 4.1 on 2022-10-07 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_user'),
        ('palindrome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='palindrome',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='palindrome',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
