# Generated by Django 4.1 on 2022-10-10 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_user'),
        ('palindrome', '0002_alter_palindrome_options_palindrome_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palindrome',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
